//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeasarApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeasarApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aaron
        ///ab
        ///abandoned
        ///abc
        ///aberdeen
        ///abilities
        ///ability
        ///able
        ///aboriginal
        ///abortion
        ///about
        ///above
        ///abraham
        ///abroad
        ///abs
        ///absence
        ///absent
        ///absolute
        ///absolutely
        ///absorption
        ///abstract
        ///abstracts
        ///abu
        ///abuse
        ///ac
        ///academic
        ///academics
        ///academy
        ///acc
        ///accent
        ///accept
        ///acceptable
        ///acceptance
        ///accepted
        ///accepting
        ///accepts
        ///access
        ///accessed
        ///accessibility
        ///accessible
        ///accessing
        ///accessories
        ///accessory
        ///accident
        ///accidents
        ///accommodate
        ///accommodation
        ///accommodations
        ///accompanied
        ///accompanying
        ///accomplish
        ///accomplished
        ///accordance
        ///according
        ///accordingly
        ///account
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а
        ///ба
        ///аба
        ///кааба
        ///баба
        ///бой-баба
        ///даба
        ///жаба
        ///раба
        ///полнеба
        ///треба
        ///потреба
        ///амёба
        ///учёба
        ///божба
        ///ворожба
        ///служба
        ///метеослужба
        ///дружба
        ///тяжба
        ///изба
        ///триба
        ///диатриба
        ///лайба
        ///шайба
        ///планшайба
        ///ройба
        ///надолба
        ///колба
        ///полба
        ///амба
        ///дамба
        ///бомба
        ///катакомба
        ///пломба
        ///гекатомба
        ///клумба
        ///румба
        ///тумба
        ///блямба
        ///оба
        ///жадоба
        ///сдоба
        ///худоба
        ///стыдоба
        ///скоба
        ///жалоба
        ///злоба
        ///зазноба
        ///роба
        ///хвороба
        ///проба
        ///утроба
        ///особа
        ///чащоба
        ///чищоба
        ///трущоба
        ///арба
        ///верба
        ///дерба
        ///торба
        ///губа
        ///пагуба
        ///палуба
        ///голуба
        ///йоруба
        ///труба
        ///стереотр [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
    }
}
